name: build

on:
  push:
    branches: [ "healtcheck-selenium" ]
  pull_request:
    branches: [ "healtcheck-selenium" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
