name: healthcheck
on:
  push:
    branches:
      - healthcheck-selenium
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
       # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
       python-version: 3.10.x
    - name: Perform a test execution
      run: |
          chromedriver -v
          cd
          pip list
          python -m robot --pythonpath . -x outputxunit.xml .
      shell: powershell

